/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CricketBookingSuccessRouteImport } from './routes/cricket-booking-success'
import { Route as CricketCheckoutRouteImport } from './routes/cricket-checkout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MyBookingsRouteImport } from './routes/my-bookings'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as CricketIndexRouteImport } from './routes/cricket/index'
import { Route as CricketMatchIdRouteImport } from './routes/cricket/$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketBookingSuccessRoute = CricketBookingSuccessRouteImport.update({
  id: '/cricket-booking-success',
  path: '/cricket-booking-success',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketCheckoutRoute = CricketCheckoutRouteImport.update({
  id: '/cricket-checkout',
  path: '/cricket-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBookingsRoute = MyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketIndexRoute = CricketIndexRouteImport.update({
  id: '/cricket/',
  path: '/cricket/',
  getParentRoute: () => rootRouteImport,
} as any)
const CricketMatchIdRoute = CricketMatchIdRouteImport.update({
  id: '/cricket/$matchId',
  path: '/cricket/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cricket-booking-success': typeof CricketBookingSuccessRoute
  '/cricket-checkout': typeof CricketCheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/reminders': typeof RemindersRoute
  '/cricket/$matchId': typeof CricketMatchIdRoute
  '/cricket/': typeof CricketIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cricket-booking-success': typeof CricketBookingSuccessRoute
  '/cricket-checkout': typeof CricketCheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/reminders': typeof RemindersRoute
  '/cricket/$matchId': typeof CricketMatchIdRoute
  '/cricket': typeof CricketIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/cricket-booking-success': typeof CricketBookingSuccessRoute
  '/cricket-checkout': typeof CricketCheckoutRoute
  '/login': typeof LoginRoute
  '/my-bookings': typeof MyBookingsRoute
  '/reminders': typeof RemindersRoute
  '/cricket/$matchId': typeof CricketMatchIdRoute
  '/cricket/': typeof CricketIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cricket-booking-success'
    | '/cricket-checkout'
    | '/login'
    | '/my-bookings'
    | '/reminders'
    | '/cricket/$matchId'
    | '/cricket/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cricket-booking-success'
    | '/cricket-checkout'
    | '/login'
    | '/my-bookings'
    | '/reminders'
    | '/cricket/$matchId'
    | '/cricket'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cricket-booking-success'
    | '/cricket-checkout'
    | '/login'
    | '/my-bookings'
    | '/reminders'
    | '/cricket/$matchId'
    | '/cricket/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CricketBookingSuccessRoute: typeof CricketBookingSuccessRoute
  CricketCheckoutRoute: typeof CricketCheckoutRoute
  LoginRoute: typeof LoginRoute
  MyBookingsRoute: typeof MyBookingsRoute
  RemindersRoute: typeof RemindersRoute
  CricketMatchIdRoute: typeof CricketMatchIdRoute
  CricketIndexRoute: typeof CricketIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-booking-success': {
      id: '/cricket-booking-success'
      path: '/cricket-booking-success'
      fullPath: '/cricket-booking-success'
      preLoaderRoute: typeof CricketBookingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket-checkout': {
      id: '/cricket-checkout'
      path: '/cricket-checkout'
      fullPath: '/cricket-checkout'
      preLoaderRoute: typeof CricketCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bookings': {
      id: '/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof MyBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket/': {
      id: '/cricket/'
      path: '/cricket'
      fullPath: '/cricket/'
      preLoaderRoute: typeof CricketIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cricket/$matchId': {
      id: '/cricket/$matchId'
      path: '/cricket/$matchId'
      fullPath: '/cricket/$matchId'
      preLoaderRoute: typeof CricketMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CricketBookingSuccessRoute: CricketBookingSuccessRoute,
  CricketCheckoutRoute: CricketCheckoutRoute,
  LoginRoute: LoginRoute,
  MyBookingsRoute: MyBookingsRoute,
  RemindersRoute: RemindersRoute,
  CricketMatchIdRoute: CricketMatchIdRoute,
  CricketIndexRoute: CricketIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
